### ISSUE TITLE
Wrong footprints for 0805 LEDs

### ISSUE THREAD

**Issue by hwreverse** [TomKeddie/prj-kicad-jlcpcb#2]
Hi, the basic LED library **jlcpcb-basic-led.lib** has a few errors:

Every 0805 LED has a link to a wrong footprint => **LED_0805_1608Metric** (this footprint does not exist in nature)

The correct footprint for these LEDs should be **LED_0805_2012Metric**

best regards,

Alexander

**Comment by TomKeddie** [comment]
@hwreverse thanks for catching this, sorry it took me so long to address.
